package mercadinhodb;

import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Produto;
import model.bean.ProdutosDeletados;
import model.dao.ProdutoDAO;
import model.dao.ProdutosDeletadosDAODescontinuado;

public class ViewCadastroProdutosDB extends javax.swing.JFrame {

    public ViewCadastroProdutosDB() {
        initComponents();
        setResizable(false);
        readTable();
        setUsuarioLogado();
    }
    
    public void readTable(){
        DefaultTableModel modelo = (DefaultTableModel) jProductTable.getModel();
        
        modelo.setNumRows(0);
        
        ProdutoDAO pdao = new ProdutoDAO();
        
        for(Produto p : pdao.read()){
            modelo.addRow(new Object[]{p.getId(), p.getDescricao(), p.getQuantidade(), p.getPreco(), p.getCriacao(), p.getAlteracao()});
        }
        
    }
    
    public void readSearch(String desc){
        DefaultTableModel modelo = (DefaultTableModel) jProductTable.getModel();
        
        modelo.setNumRows(0);
        
        ProdutoDAO pdao = new ProdutoDAO();
        
        for(Produto p : pdao.search(desc)){
            modelo.addRow(new Object[]{p.getId(), p.getDescricao(), p.getQuantidade(), p.getPreco(), p.getCriacao(), p.getAlteracao()});
        }
        
    }
    
    public void setUsuarioLogado(){
        UsuarioLogadotxt.setText(ViewLauncherDB.Login_User);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        txtPreco = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        jBotCadastrar = new javax.swing.JButton();
        jBotDeletar = new javax.swing.JButton();
        jBotAtualizar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        botao_Buscar = new javax.swing.JButton();
        txtBusca = new javax.swing.JTextField();
        botao_resetarBusca = new javax.swing.JButton();
        UsuarioLogadotxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jProductTable = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        botaoHome = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        CadastroUser = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        ProdutosDeletados = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(180, 205, 255));

        txtPreco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });
        txtPreco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecoKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("DESCRIÇÃO DO PRODUTO");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("QUANTIDADE (UN)");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("PREÇO (R$)");

        txtDesc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescActionPerformed(evt);
            }
        });
        txtDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescKeyPressed(evt);
            }
        });

        txtQuantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });
        txtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyPressed(evt);
            }
        });

        jBotCadastrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBotCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jBotCadastrar.setText("Cadastrar");
        jBotCadastrar.setToolTipText("Adiciona na tabela do banco de dados um novo produto com os valores digitados nos campos");
        jBotCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotCadastrarActionPerformed(evt);
            }
        });

        jBotDeletar.setBackground(new java.awt.Color(255, 102, 51));
        jBotDeletar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBotDeletar.setForeground(new java.awt.Color(255, 255, 255));
        jBotDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bin_empty.png"))); // NOI18N
        jBotDeletar.setText("Excluir Produto");
        jBotDeletar.setToolTipText("Excluir o produto selecionado da tabela");
        jBotDeletar.setMaximumSize(new java.awt.Dimension(99, 29));
        jBotDeletar.setMinimumSize(new java.awt.Dimension(99, 29));
        jBotDeletar.setPreferredSize(new java.awt.Dimension(99, 29));
        jBotDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotDeletarActionPerformed(evt);
            }
        });

        jBotAtualizar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBotAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil.png"))); // NOI18N
        jBotAtualizar.setText("Atualizar Produto");
        jBotAtualizar.setToolTipText("Atualiza o produto selecionado na tabela pelos valores atuais dos campos");
        jBotAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotAtualizarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("BASE DE DADOS - PRODUTOS");

        botao_Buscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botao_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zoom.png"))); // NOI18N
        botao_Buscar.setText("Buscar");
        botao_Buscar.setToolTipText("Busca todos os produtos que contem o que está sendo pesquisado");
        botao_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_BuscarActionPerformed(evt);
            }
        });

        txtBusca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaActionPerformed(evt);
            }
        });

        botao_resetarBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cross.png"))); // NOI18N
        botao_resetarBusca.setToolTipText("Limpa o campo de busca e mostra a tabela de produtos completa");
        botao_resetarBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_resetarBuscaActionPerformed(evt);
            }
        });

        UsuarioLogadotxt.setEditable(false);
        UsuarioLogadotxt.setBackground(new java.awt.Color(202, 202, 211));
        UsuarioLogadotxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UsuarioLogadotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioLogadotxtActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("LOGADO COMO:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emoticon_grin.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 74, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(533, 533, 533)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(77, 77, 77))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jBotAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jBotCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(185, 185, 185)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jBotDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botao_resetarBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(botao_Buscar)
                        .addGap(101, 101, 101))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsuarioLogadotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UsuarioLogadotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtDesc)
                    .addComponent(txtPreco, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botao_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botao_resetarBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBotCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBotAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(jBotDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jProductTable.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DESCRIÇÃO", "QUANTIDADE", "PREÇO (R$)", "CRIADOR", "ALTERAÇÃO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jProductTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jProductTableMouseReleased(evt);
            }
        });
        jProductTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jProductTableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jProductTable);
        if (jProductTable.getColumnModel().getColumnCount() > 0) {
            jProductTable.getColumnModel().getColumn(0).setMinWidth(70);
            jProductTable.getColumnModel().getColumn(0).setMaxWidth(70);
            jProductTable.getColumnModel().getColumn(1).setResizable(false);
            jProductTable.getColumnModel().getColumn(2).setMinWidth(110);
            jProductTable.getColumnModel().getColumn(2).setMaxWidth(110);
            jProductTable.getColumnModel().getColumn(3).setMinWidth(90);
            jProductTable.getColumnModel().getColumn(3).setMaxWidth(90);
            jProductTable.getColumnModel().getColumn(4).setMinWidth(110);
            jProductTable.getColumnModel().getColumn(4).setMaxWidth(110);
            jProductTable.getColumnModel().getColumn(5).setMinWidth(110);
            jProductTable.getColumnModel().getColumn(5).setMaxWidth(110);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jToolBar1.setFloatable(false);
        jToolBar1.add(jSeparator4);

        botaoHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/house.png"))); // NOI18N
        botaoHome.setText("Home");
        botaoHome.setFocusable(false);
        botaoHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoHomeActionPerformed(evt);
            }
        });
        jToolBar1.add(botaoHome);
        jToolBar1.add(jSeparator5);

        CadastroUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        CadastroUser.setText("Usuários");
        CadastroUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CadastroUser.setFocusable(false);
        CadastroUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CadastroUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CadastroUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroUserActionPerformed(evt);
            }
        });
        jToolBar1.add(CadastroUser);
        jToolBar1.add(jSeparator1);

        ProdutosDeletados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bin.png"))); // NOI18N
        ProdutosDeletados.setText("Produtos Inativos");
        ProdutosDeletados.setFocusable(false);
        ProdutosDeletados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ProdutosDeletados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ProdutosDeletados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutosDeletadosActionPerformed(evt);
            }
        });
        jToolBar1.add(ProdutosDeletados);
        jToolBar1.add(jSeparator2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jProductTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProductTableMouseReleased
        
        if(jProductTable.getSelectedRow() != -1){
            txtDesc.setText(jProductTable.getValueAt(jProductTable.getSelectedRow(), 1).toString());
            txtQuantidade.setText(jProductTable.getValueAt(jProductTable.getSelectedRow(),2).toString());
            txtPreco.setText(jProductTable.getValueAt(jProductTable.getSelectedRow(), 3).toString());
        }
        
    }//GEN-LAST:event_jProductTableMouseReleased

    private void jProductTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jProductTableKeyReleased
        
        if(jProductTable.getSelectedRow() != -1){
            txtDesc.setText(jProductTable.getValueAt(jProductTable.getSelectedRow(), 1).toString());
            txtQuantidade.setText(jProductTable.getValueAt(jProductTable.getSelectedRow(), 2).toString());
            txtPreco.setText(jProductTable.getValueAt(jProductTable.getSelectedRow(), 3).toString());
        }
        
    }//GEN-LAST:event_jProductTableKeyReleased

    private void jBotAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotAtualizarActionPerformed

        if(jProductTable.getSelectedRow() != -1){

            if("".equals(txtDesc.getText()) || "".equals(txtQuantidade.getText()) || "".equals(txtPreco.getText())){
                JOptionPane.showMessageDialog(null, "Preencha os campos para atualizar este produto");
            }
            else{
                Produto p = new Produto();
                ProdutoDAO dao = new ProdutoDAO();

                p.setAlteracao(ViewLauncherDB.Login_User);
                p.setId((int) jProductTable.getValueAt(jProductTable.getSelectedRow(), 0));
                p.setDescricao(txtDesc.getText());
                p.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
                p.setPreco(Double.parseDouble(txtPreco.getText()));

                dao.update(p);
                txtDesc.setText("");
                txtQuantidade.setText("");
                txtPreco.setText("");
                readTable();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione um produto para atualizar!");
        }
    }//GEN-LAST:event_jBotAtualizarActionPerformed

    private void jBotDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotDeletarActionPerformed

        if(jProductTable.getSelectedRow() != -1){

            Produto p = new Produto();
            ProdutoDAO dao = new ProdutoDAO();
            
//            ProdutosDeletados prodel = new ProdutosDeletados();
//            ProdutosDeletadosDAODescontinuado deldao = new ProdutosDeletadosDAODescontinuado();
//
//            prodel.setResponsavel(ViewLauncherDB.Login_User);
//            prodel.setDescricao_del(txtDesc.getText());
//            prodel.setQuantidade_del(Integer.parseInt(txtQuantidade.getText()));
//            prodel.setPreco_del(Double.parseDouble(txtPreco.getText()));
//            
//            deldao.create(prodel);
            
            p.setId((int) jProductTable.getValueAt(jProductTable.getSelectedRow(), 0));
            
            dao.delete(p);
            
            txtDesc.setText("");
            txtQuantidade.setText("");
            txtPreco.setText("");
            
            readTable();

        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir!");
        }
    }//GEN-LAST:event_jBotDeletarActionPerformed

    private void jBotCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotCadastrarActionPerformed

        if("".equals(txtDesc.getText()) || "".equals(txtQuantidade.getText()) || "".equals(txtPreco.getText())){
            JOptionPane.showMessageDialog(null, "Preencha todas os campos.");
        }
        else{
            Produto p = new Produto();
            ProdutoDAO dao = new ProdutoDAO();

            p.setCriacao(ViewLauncherDB.Login_User);
            p.setDescricao(txtDesc.getText());
            p.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
            p.setPreco(Double.parseDouble(txtPreco.getText()));

            dao.create(p);
            txtDesc.setText("");
            txtQuantidade.setText("");
            txtPreco.setText("");
            txtDesc.grabFocus();
            readTable();
        }
    }//GEN-LAST:event_jBotCadastrarActionPerformed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void txtDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaActionPerformed

    private void botao_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_BuscarActionPerformed
        
        readSearch(txtBusca.getText());
        
    }//GEN-LAST:event_botao_BuscarActionPerformed

    private void botao_resetarBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_resetarBuscaActionPerformed
        
        txtBusca.setText("");
        readTable();
        
    }//GEN-LAST:event_botao_resetarBuscaActionPerformed

    private void botaoHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoHomeActionPerformed
        this.dispose();
        new ViewDashboardDB().setVisible(true);
    }//GEN-LAST:event_botaoHomeActionPerformed

    private void CadastroUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroUserActionPerformed
        this.dispose();
        new ViewLoginCadastroDB().setVisible(true);
        
    }//GEN-LAST:event_CadastroUserActionPerformed

    private void ProdutosDeletadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutosDeletadosActionPerformed
        this.dispose();
        new ViewProdutosDeletadosDB().setVisible(true);
    }//GEN-LAST:event_ProdutosDeletadosActionPerformed

    private void txtDescKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            if("".equals(txtDesc.getText()) || "".equals(txtQuantidade.getText()) || "".equals(txtPreco.getText())){
                JOptionPane.showMessageDialog(null, "Preencha todas os campos.");
            }
            else{
                Produto p = new Produto();
                ProdutoDAO dao = new ProdutoDAO();

                p.setCriacao(ViewLauncherDB.Login_User);
                p.setDescricao(txtDesc.getText());
                p.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
                p.setPreco(Double.parseDouble(txtPreco.getText()));

                dao.create(p);
                txtDesc.setText("");
                txtQuantidade.setText("");
                txtPreco.setText("");
                txtDesc.grabFocus();
                readTable();
            }
        }
        
    }//GEN-LAST:event_txtDescKeyPressed

    private void txtQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            if("".equals(txtDesc.getText()) || "".equals(txtQuantidade.getText()) || "".equals(txtPreco.getText())){
                JOptionPane.showMessageDialog(null, "Preencha todas os campos.");
            }
            else{
                Produto p = new Produto();
                ProdutoDAO dao = new ProdutoDAO();

                p.setCriacao(ViewLauncherDB.Login_User);
                p.setDescricao(txtDesc.getText());
                p.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
                p.setPreco(Double.parseDouble(txtPreco.getText()));

                dao.create(p);
                txtDesc.setText("");
                txtQuantidade.setText("");
                txtPreco.setText("");
                txtDesc.grabFocus();
                readTable();
            }
        }
        
    }//GEN-LAST:event_txtQuantidadeKeyPressed

    private void txtPrecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecoKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            if("".equals(txtDesc.getText()) || "".equals(txtQuantidade.getText()) || "".equals(txtPreco.getText())){
                JOptionPane.showMessageDialog(null, "Preencha todas os campos.");
            }
            else{
                Produto p = new Produto();
                ProdutoDAO dao = new ProdutoDAO();

                p.setCriacao(ViewLauncherDB.Login_User);
                p.setDescricao(txtDesc.getText());
                p.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
                p.setPreco(Double.parseDouble(txtPreco.getText()));

                dao.create(p);
                txtDesc.setText("");
                txtQuantidade.setText("");
                txtPreco.setText("");
                txtDesc.grabFocus();
                readTable();
            }
        }
        
    }//GEN-LAST:event_txtPrecoKeyPressed

    private void UsuarioLogadotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioLogadotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioLogadotxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroProdutosDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroProdutosDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroProdutosDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroProdutosDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCadastroProdutosDB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastroUser;
    private javax.swing.JButton ProdutosDeletados;
    private javax.swing.JTextField UsuarioLogadotxt;
    private javax.swing.JButton botaoHome;
    private javax.swing.JButton botao_Buscar;
    private javax.swing.JButton botao_resetarBusca;
    private javax.swing.JButton jBotAtualizar;
    private javax.swing.JButton jBotCadastrar;
    private javax.swing.JButton jBotDeletar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JTable jProductTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
