/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mercadinhodb;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Usuario;
import model.dao.UsuarioDAO;

/**
 *
 * @author Henrique Oliveira
 */
public class ViewCadastroUsuarioDB extends javax.swing.JFrame {

    /**
     * Creates new form ViewCadastroUsuarioDB
     */
    public ViewCadastroUsuarioDB() {
        setResizable(false);
        initComponents();
        readTable();
        adminLogado();
        ComboBox.setSelectedIndex(-1);
    }
    
    public void readTable(){
        DefaultTableModel modelo = (DefaultTableModel) UserTable.getModel();
        
        modelo.setNumRows(0);
        
        UsuarioDAO udao = new UsuarioDAO();
        
        for(Usuario u : udao.readUser()){
            switch(u.getAdmin()){
                case 0:
                    modelo.addRow(new Object[]{u.getLogin_usuario(), u.getSenha(), "Administrador"});
                    break;
                    
                case 1:
                    modelo.addRow(new Object[]{u.getLogin_usuario(), u.getSenha(), "Usuário"});
                    break;
                    
                case 2:
                    modelo.addRow(new Object[]{u.getLogin_usuario(), u.getSenha(), "Caixa"});
                    break;
                    
                default:
                    modelo.addRow(new Object[]{u.getLogin_usuario(), u.getSenha(), "Sem função"});
                    break;
            }
        }
        
    }
    
    public void readSearch(String desc){
        DefaultTableModel modelo = (DefaultTableModel) UserTable.getModel();
        
        modelo.setNumRows(0);
        
        UsuarioDAO udao = new UsuarioDAO();
        
        for(Usuario u : udao.search(desc)){
            if(u.getAdmin() == 0){
                modelo.addRow(new Object[]{u.getLogin_usuario(), u.getSenha(), "Usuário"});
            }
            else{
                modelo.addRow(new Object[]{u.getLogin_usuario(), u.getSenha(), "Administrador"});
            }
        }
        
    }
    
    public void adminLogado(){
        AdminLogadotxt.setText(ViewLauncherDB.Login_Admin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        UserTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        botao_Cadastrar = new javax.swing.JButton();
        botao_Remover_Usuario = new javax.swing.JButton();
        botao_Atualizar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        botao_Buscar_Usuario = new javax.swing.JButton();
        botao_Resetar_Busca = new javax.swing.JButton();
        txtBuscaUser = new javax.swing.JTextField();
        AdminLogadotxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        BotaoHome = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        botaoProdutos = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UserTable.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        UserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LOGIN", "SENHA", "PRIVILÉGIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        UserTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                UserTableMouseReleased(evt);
            }
        });
        UserTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                UserTableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(UserTable);
        if (UserTable.getColumnModel().getColumnCount() > 0) {
            UserTable.getColumnModel().getColumn(0).setMinWidth(240);
            UserTable.getColumnModel().getColumn(0).setMaxWidth(240);
            UserTable.getColumnModel().getColumn(1).setResizable(false);
            UserTable.getColumnModel().getColumn(2).setMinWidth(130);
            UserTable.getColumnModel().getColumn(2).setMaxWidth(130);
        }

        jPanel2.setBackground(new java.awt.Color(180, 205, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("LOGIN DO USUÁRIO");

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        botao_Cadastrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botao_Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_add.png"))); // NOI18N
        botao_Cadastrar.setText("Cadastrar");
        botao_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_CadastrarActionPerformed(evt);
            }
        });

        botao_Remover_Usuario.setBackground(new java.awt.Color(255, 102, 51));
        botao_Remover_Usuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botao_Remover_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        botao_Remover_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_delete.png"))); // NOI18N
        botao_Remover_Usuario.setText("Remover");
        botao_Remover_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_Remover_UsuarioActionPerformed(evt);
            }
        });

        botao_Atualizar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botao_Atualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_edit.png"))); // NOI18N
        botao_Atualizar.setText("Atualizar");
        botao_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_AtualizarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("SENHA");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BASE DE DADOS - USUÁRIOS");

        botao_Buscar_Usuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botao_Buscar_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zoom.png"))); // NOI18N
        botao_Buscar_Usuario.setText("Buscar");
        botao_Buscar_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_Buscar_UsuarioActionPerformed(evt);
            }
        });

        botao_Resetar_Busca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cross.png"))); // NOI18N
        botao_Resetar_Busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_Resetar_BuscaActionPerformed(evt);
            }
        });

        txtBuscaUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        AdminLogadotxt.setEditable(false);
        AdminLogadotxt.setBackground(new java.awt.Color(202, 202, 211));
        AdminLogadotxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AdminLogadotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLogadotxtActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("CADASTRAR NO NOME DE:");

        ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 - Usuário", "2 - Caixa" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("FUNÇÃO:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSenha, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botao_Cadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botao_Atualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botao_Remover_Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addGap(73, 73, 73))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AdminLogadotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(botao_Resetar_Busca, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(txtBuscaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(botao_Buscar_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminLogadotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botao_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botao_Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botao_Remover_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(54, 54, 54)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botao_Buscar_Usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtBuscaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(botao_Resetar_Busca, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGap(29, 29, 29))
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jToolBar1.add(jSeparator1);

        BotaoHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/house.png"))); // NOI18N
        BotaoHome.setText("Home");
        BotaoHome.setFocusable(false);
        BotaoHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotaoHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotaoHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoHomeActionPerformed(evt);
            }
        });
        jToolBar1.add(BotaoHome);
        jToolBar1.add(jSeparator2);

        botaoProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/database_add.png"))); // NOI18N
        botaoProdutos.setText("Produtos");
        botaoProdutos.setFocusable(false);
        botaoProdutos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoProdutos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProdutosActionPerformed(evt);
            }
        });
        jToolBar1.add(botaoProdutos);
        jToolBar1.add(jSeparator3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botao_Remover_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_Remover_UsuarioActionPerformed
        
        if(UserTable.getSelectedRow() != -1){

            Usuario u = new Usuario();
            UsuarioDAO udao = new UsuarioDAO();

            u.setLogin_usuario((String) UserTable.getValueAt(UserTable.getSelectedRow(), 0));

            udao.deleteUser(u);
            txtUsuario.setText("");
            txtSenha.setText("");
            readTable();

        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir!");
        }
        
    }//GEN-LAST:event_botao_Remover_UsuarioActionPerformed

    private void botao_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_CadastrarActionPerformed
        
        if("".equals(txtUsuario.getText()) || "".equals(txtSenha.getText())){
            JOptionPane.showMessageDialog(null, "Preencha todas os campos.");
        }
        else{
            Usuario u = new Usuario();
            UsuarioDAO udao = new UsuarioDAO();
            
            if("1 - Usuário".equals(ComboBox.getSelectedItem().toString())){
                u.setAdmin(1);
            }
            else if("2 - Caixa".equals(ComboBox.getSelectedItem().toString())){
                u.setAdmin(2);
            }
            
            u.setLogin_usuario(txtUsuario.getText());
            u.setSenha(txtSenha.getText());
            
            udao.createUser(u);
            txtUsuario.setText("");
            txtSenha.setText("");
            ComboBox.setSelectedIndex(-1);
            readTable();
        }
        
    }//GEN-LAST:event_botao_CadastrarActionPerformed

    private void BotaoHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoHomeActionPerformed
        this.dispose();
        new ViewDashboardDB().setVisible(true);
    }//GEN-LAST:event_BotaoHomeActionPerformed

    private void UserTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UserTableKeyReleased
        
        if(UserTable.getSelectedRow() != -1){
            txtUsuario.setText(UserTable.getValueAt(UserTable.getSelectedRow(), 0).toString());
            txtSenha.setText(UserTable.getValueAt(UserTable.getSelectedRow(), 1).toString());
        }
        
    }//GEN-LAST:event_UserTableKeyReleased

    private void UserTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserTableMouseReleased
        
        if(UserTable.getSelectedRow() != -1){
            txtUsuario.setText(UserTable.getValueAt(UserTable.getSelectedRow(), 0).toString());
            txtSenha.setText(UserTable.getValueAt(UserTable.getSelectedRow(), 1).toString());
        }
        
    }//GEN-LAST:event_UserTableMouseReleased

    private void botao_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_AtualizarActionPerformed
        
        if(UserTable.getSelectedRow() != -1){

            if("".equals(txtUsuario.getText()) || "".equals(txtSenha.getText())){
                JOptionPane.showMessageDialog(null, "Preencha os campos para atualizar este usuario");
            }
            else{
                Usuario u = new Usuario();
                UsuarioDAO udao = new UsuarioDAO();
                
                u.setLogin_usuario(txtUsuario.getText());
                u.setSenha(txtSenha.getText());
                udao.updateUser(u);
                txtUsuario.setText("");
                txtSenha.setText("");
                readTable();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione um produto para atualizar!");
        }
        
    }//GEN-LAST:event_botao_AtualizarActionPerformed

    private void botao_Resetar_BuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_Resetar_BuscaActionPerformed
        
        txtBuscaUser.setText("");
        readTable();
        
    }//GEN-LAST:event_botao_Resetar_BuscaActionPerformed

    private void botao_Buscar_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_Buscar_UsuarioActionPerformed
        
        readSearch(txtBuscaUser.getText());
        
    }//GEN-LAST:event_botao_Buscar_UsuarioActionPerformed

    private void AdminLogadotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLogadotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminLogadotxtActionPerformed

    private void botaoProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProdutosActionPerformed
        this.dispose();
        new ViewCadastroProdutosDB().setVisible(true);   
    }//GEN-LAST:event_botaoProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroUsuarioDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroUsuarioDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroUsuarioDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroUsuarioDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCadastroUsuarioDB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdminLogadotxt;
    private javax.swing.JButton BotaoHome;
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JTable UserTable;
    private javax.swing.JButton botaoProdutos;
    private javax.swing.JButton botao_Atualizar;
    private javax.swing.JButton botao_Buscar_Usuario;
    private javax.swing.JButton botao_Cadastrar;
    private javax.swing.JButton botao_Remover_Usuario;
    private javax.swing.JButton botao_Resetar_Busca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField txtBuscaUser;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
